# Generated by Django 5.2.7 on 2025-12-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
