# Generated by Django 5.2.7 on 2025-12-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
